<a href="https://colab.research.google.com/github/Kausharalam7/Data-Science/blob/main/1_0_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to NumPy**

NumPy stands for Numerical Python, is an open-source library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

In [1]:
# installation of numpy
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
# importing numpy
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]

In [ ]:
# array attributes
print(arr2.ndim)    # Number of dimensions
print(arr2.shape)   # Shape of the array
print(arr2.size)    # Total number of elements
print(arr2.dtype)   # Data type of elements
print(arr2.itemsize) # Size of each element in bytes
print(arr2.nbytes)   # Total bytes consumed by the array

2
(2, 3)
6
int64
8
48

In [ ]:
# We can create NumPy arrays from Python lists or tuples using the array() function.

# from a list
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(arr1)

# from a tuple
tuple1=(3,4,5,67,8)
arr2=np.array(tuple1)
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

[1 2 3 4 5]
[ 3  4  5 67  8]
(5,)
1
5

Using Built-in Functions

NumPy provides several functions to create arrays with specific patterns or values.


1. zeros(): Create an array filled with zeros.

2. ones(): Create an array filled with ones.

3. arange(): Create an array with a range of values.

4. linspace(): Create an array with a specified number of evenly spaced values.

5. eye(): Create an identity matrix.

In [ ]:
zeros_arr=np.zeros((2,3))
print(zeros_arr)

ones_arr=np.ones((2,4))
print(ones_arr)

range_arr=np.arange(1,10,2)
print(range_arr)

linspace_arr=np.linspace(0,10,5)  # Array with evenly spaced values
print(linspace_arr)

eye_arr=np.eye(3) # identity matrix
print(eye_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
## Using random numbers
# random integers
rand_int=np.random.randint(0,10,size=(3,3))
print(rand_int)

## random floats
rand_float=np.random.random((2,3))
print(rand_float)

[[0 4 5]
 [9 5 0]
 [5 3 6]]
[[0.15170183 0.8196846  0.39589282]
 [0.61289251 0.21347066 0.6006217 ]]

In [ ]:
# Array indexing and slicing
arr=np.array([11,22,33,44,55,66,77,88,99])
print(arr[0]) # first element
print(arr[-1]) # last element

print(arr[2:7])
print(arr[:5])
print(arr[5:])

# for multidimensional
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3[0,2])
print(arr3[0,:])
print(arr3[:,2])

11
99
[33 44 55 66 77]
[11 22 33 44 55]
[66 77 88 99]
3
[1 2 3]
[3 6]

In [ ]:
## Boolean Indexing
arr5=np.array([10,20,30,40,50])
print(arr5[arr5>30])
print(arr5[(arr5>=20) & ( arr5<40)])

# for multidimensional arrays
arr6=np.array([[1,5,3,],[2,3,4],[3,5,7]])
print(arr6[arr6>2])
arr6[arr6 > 4] = 0
print(arr6)

[40 50]
[20 30]
[5 3 3 4 3 5 7]
[[1 0 3]
 [2 3 4]
 [3 0 0]]

In [ ]:
# array operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr2 / arr1)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]

In [ ]:
# Allows arithmetic operations between arrays of different shapes
arr = np.array([1, 2, 3])
scalar = 2
print(arr + scalar)
print(arr*scalar)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
print(arr2 + scalar)
print(arr2*scalar)

[3 4 5]
[2 4 6]
[[11 12 13]
 [14 15 16]]
[[10 20 30]
 [40 50 60]]

In [ ]:
# Universal Function
arr=np.array([1,4,9,16,25,49,81,36,225])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.tan(arr))
print(np.sin(arr))
print(np.cos(arr))

[ 1.  2.  3.  4.  5.  7.  9.  6. 15.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.8918203
 4.39444915 3.58351894 5.4161004 ]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 1.90734657e+21 1.50609731e+35 4.31123155e+15
 5.20305514e+97]
[ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641 -3.17290855
 -0.81099442  7.75047091 -2.53211499]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175 -0.95375265
 -0.62988799 -0.99177885 -0.93009488]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281  0.30059254
  0.77668598 -0.12796369  0.36731937]

In [ ]:
# reshapings arrays
arr=np.arange(1,10)
reshaped=arr.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
# Flatten -- > Convert a multi-dimensional array into a 1D array.
arr=np.array([[2,3,4,5],[2,3,4,5]])
print(arr.flatten())

[2 3 4 5 2 3 4 5]

In [ ]:
# Transpose
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr2.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]

Stacking and Splitting Arrays

Stacking

Combine multiple arrays into one.


1. np.vstack(): Stack arrays vertically (row-wise).

2. np.hstack(): Stack arrays horizontally (column-wise).

3. np.concatenate(): General-purpose concatenation along an existing axis.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
v_stack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", v_stack)
h_stack = np.hstack((arr1, arr2))
print("Horizontal Stack:", h_stack)
# Concatenate along axis 0
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
print("Concatenate Axis 0:", concat_axis0)
# Concatenate along axis 1
arr3 = np.array([[7, 8, 9], [10, 11, 12]])
concat_axis1 = np.concatenate((arr1.reshape(1, -1), arr3), axis=0)
print("Concatenate Axis 0 with 2D Array:\n", concat_axis1)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]
Concatenate Axis 0: [1 2 3 4 5 6]
Concatenate Axis 0 with 2D Array:
 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]

Splitting

Divide an array into multiple sub-arrays.


1. np.split(): Split array into equal parts.

2. np.hsplit(): Split array horizontally.

3. np.vsplit(): Split array vertically.

In [ ]:
arr=np.arange(10,42)
#split into 4 equal parts
splits=np.split(arr,4)
for i in splits:
  print(i)

# Split a 2D array horizontally
arr2d = np.array([[1, 2, 3, 4,3,5], [5, 6, 7,4,5, 8]])
hsplits = np.hsplit(arr2d, 3)
for j in hsplits:
    print("Horizontal Split:\n", j)

# Split a 2D array vertically
vsplits = np.vsplit(arr2d, 2)
for k in vsplits:
    print("Vertical Split:\n", k)

[10 11 12 13 14 15 16 17]
[18 19 20 21 22 23 24 25]
[26 27 28 29 30 31 32 33]
[34 35 36 37 38 39 40 41]
Horizontal Split:
 [[1 2]
 [5 6]]
Horizontal Split:
 [[3 4]
 [7 4]]
Horizontal Split:
 [[3 5]
 [5 8]]
Vertical Split:
 [[1 2 3 4 3 5]]
Vertical Split:
 [[5 6 7 4 5 8]]

Linear Alegebra with NumPy

In [ ]:
# Dot product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot = np.dot(arr1, arr2)
print("Dot Product:", dot)

# For 2D arrays
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_matrix = np.dot(matrix1, matrix2)
print("Dot Product of Matrices:\n", dot_matrix)

Dot Product: 32
Dot Product of Matrices:
 [[19 22]
 [43 50]]

In [ ]:
# Matrix Operations
result=matrix1 @ matrix2
print(result)

transpose=matrix1.T
print(transpose)

# inverse of a matrix
inverse=np.linalg.inv(matrix1)
print(inverse)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]

In [ ]:
# Eigenvalues and Eigenvectors
matrix = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]

In [ ]:
# Setting a seed for reproducibility
np.random.seed(142)
print("Random Integers with Seed:\n", np.random.randint(0, 10, size=5))

Random Integers with Seed:
 [5 5 0 1 2]

In [ ]:
# Random Distributions

# Normal Disrtibution
normal=np.random.normal(loc=0,scale=1, size=5)
print(normal)

#Binomial Distribution
binomial=np.random.binomial(n=10,p=0.5,size=5)
print(binomial)

# Poisson distribution
poisson=np.random.poisson(lam=3,size=5)
print(poisson)

[-1.16414473 -0.89961445  1.11003428 -1.23280523 -0.56042711]
[4 7 6 5 3]
[1 2 3 0 2]

**Common Use Cases**

In [ ]:
# Data analysis and preprocessing

# Normalization (Min-Max Scaling)
data=np.array([10,20,30,40,50])
normalized=(data-np.min(data))/(np.max(data)-np.min(data))
print("NOramlized Data:",normalized)

# Standardized (Z-score)
standarized=(data-np.mean(data))/np.std(data)
print(standarized)

NOramlized Data: [0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [ ]:
# Image Processing
image = np.array([[0, 50, 100, 150, 200],
                  [10, 60, 110, 160, 210],
                  [20, 70, 120, 170, 220],
                  [30, 80, 130, 180, 230],
                  [40, 90, 140, 190, 240]])

# Invert the image
inverted_image = 255 - image
print("Inverted Image:\n", inverted_image)

Inverted Image:
 [[255 205 155 105  55]
 [245 195 145  95  45]
 [235 185 135  85  35]
 [225 175 125  75  25]
 [215 165 115  65  15]]

In [ ]:
# Scientific Computing
# Fourier Transform
signal = np.array([0, 1, 0, -1])
ft = np.fft.fft(signal)
print("Fourier Transform:", ft)

# Polynomial Fitting
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 3, 7, 13, 21])
coefficients = np.polyfit(x, y, 2)
print("Polynomial Coefficients:", coefficients)

# Create a polynomial function
poly = np.poly1d(coefficients)
print("Polynomial Function:\n", poly)

Fourier Transform: [0.+0.j 0.-2.j 0.+0.j 0.+2.j]
Polynomial Coefficients: [1. 1. 1.]
Polynomial Function:
    2
1 x + 1 x + 1

In [ ]:
# Using a loop
arr=np.array([1,2,3,4,5,6])
result=[]
for x in arr:
  result.append(x*2)
print(result)

# Using Vectorization
vectorized=arr*2
print(vectorized)

[2, 4, 6, 8, 10, 12]
[ 2  4  6  8 10 12]

In [ ]:
arr=np.array([1,2,3],dtype=np.int32)
print(arr.dtype)

int32

### **Introduction to Pandas**

Pandas is an open-source Python library providing high-performance, easy-to-use data structures, and data analysis tools. It is built on top of NumPy and integrates well with many other libraries in the Python ecosystem, making it essential for data science and analytics.

In [ ]:
# installation of pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

**Data Structure**

1. Series
2. DataFrame

In [ ]:
# Series
# A Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating-point numbers, Python objects, etc.).
# It can be thought of as a column in a spreadsheet or a database table.
import pandas as pd

# Creating a Series from a list
s = pd.Series(data, index=None)

In [ ]:
# Creating a Series from a list
s = pd.Series([1, 3, 5, 7, 9])
print(s)

# Creating a Series with custom index
s_custom = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd', 'e'])
print(s_custom)

0    1
1    3
2    5
3    7
4    9
dtype: int64
a    1
b    3
c    5
d    7
e    9
dtype: int64

In [ ]:
# DataFrame
# A DataFrame is a two-dimensional labeled data structure with columns that can be of different types.
# It is similar to a table in a relational database or a spreadsheet in Excel. DataFrames are the primary data structure in Pandas for handling structured data.


# Creating a DataFrame from a dictionary
df = pd.DataFrame(data, index=None, columns=None)

In [ ]:
# creating a Dataframe from  a dictionary
data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[12,2,32,35],
    'City':['New York','Los Angeles','Chicago',"Patna"]
}
df=pd.DataFrame(data)
print(df)

# creating a dataframe with custom index
df_custom_index=pd.DataFrame(data,index=['a','b','d','f'])
print(df_custom_index)

      Name  Age         City
0    Alice   12     New York
1      Bob    2  Los Angeles
2  Charlie   32      Chicago
3    David   35        Patna
      Name  Age         City
a    Alice   12     New York
b      Bob    2  Los Angeles
d  Charlie   32      Chicago
f    David   35        Patna

Key Differences Between Series and DataFrame

Dimension:

1. Series: One-dimensional (like a single column).

2. DataFrame: Two-dimensional (like a table with rows and columns).

Structure:

1. Series: Can hold a single data type.
2. DataFrame: Can hold multiple data types (different types in different columns).

Usage:

1. Series: Useful for storing and manipulating single columns of data.
2. DataFrame: Useful for handling datasets with multiple attributes.

In [ ]:
# acceising series data
# Accessing data by index
print("First element in Series:", s[0])  # Access by position
print("Element with index 'b':", s_custom['b'])  # Access by label

First element in Series: 1
Element with index 'b': 3

In [ ]:
# accessing dataframe data
# Accessing a column
print("Name Column:\n", df['Name'])

# Accessing a row
print("First Row:\n", df.iloc[0])  # Access by position
print("Row with index 'b':\n", df_custom_index.loc['b'])  # Access by label

Name Column:
 0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
First Row:
 Name       Alice
Age           12
City    New York
Name: 0, dtype: object
Row with index 'b':
 Name            Bob
Age               2
City    Los Angeles
Name: b, dtype: object

In [ ]:
data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[12,2,32,35],
    'City':['New York','Los Angeles','Chicago',"Patna"]
}
df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   12     New York
1      Bob    2  Los Angeles
2  Charlie   32      Chicago
3    David   35        Patna

In [ ]:
df.head()

      Name  Age         City
0    Alice   12     New York
1      Bob    2  Los Angeles
2  Charlie   32      Chicago
3    David   35        Patna

In [ ]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
df.index.tolist()

[0, 1, 2, 3]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [ ]:
df.describe()

            Age
count   4.00000
mean   20.25000
std    15.88238
min     2.00000
25%     9.50000
50%    22.00000
75%    32.75000
max    35.00000

In [ ]:
df.nunique()

Name    4
Age     4
City    4
dtype: int64

In [ ]:
df['Age'].unique()

array([12,  2, 32, 35])

In [ ]:
df.shape

(4, 3)

In [ ]:
df.size

12

In [ ]:
df

      Name  Age         City
0    Alice   12     New York
1      Bob    2  Los Angeles
2  Charlie   32      Chicago
3    David   35        Patna

Loading in dataframes from files

In [ ]:
coffee=pd.read_csv('/content/coffee.csv')

In [ ]:
# Accessing data wiht pandas
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [ ]:
# pass in random_state to make deterministic
coffee.sample(5)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
5   Wednesday       Latte          25
7    Thursday       Latte          30
0      Monday    Espresso          25
11   Saturday       Latte          35

In [ ]:
#loc
#coff.loc[rows,columns]
coffee.loc[3]

Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object

In [ ]:
coffee.loc[[0,1,5]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [ ]:
coffee.loc[3:6,["Day","Units Sold"]]

         Day  Units Sold
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25
6   Thursday          40

Use loc when you want to index by label and want inclusive slicing.

Use iloc when you want to index by position and want exclusive slicing.

In [ ]:
#iloc
coffee.iloc[:,[0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [ ]:
coffee.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [ ]:
coffee.iloc[1:4, coffee.columns.get_loc("Units Sold")] = 10

Use at for label-based access to single values.

Use iat for position-based access to single values.

In [ ]:

coffee.at[0,coffee.columns.get_loc("Units Sold")] = 10
coffee.iat[3,1]

'Latte'

In [ ]:
coffee.Day

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
0                  NaN
Name: Day, dtype: object

In [ ]:
coffee["Day"]

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
0                  NaN
Name: Day, dtype: object

In [ ]:
# Sort Values
df=coffee.sort_values(["Units Sold"],ascending=False)

In [ ]:
df.head()

                 Day Coffee Type  Units Sold   2
Day
Friday        Friday    Espresso        45.0 NaN
Saturday    Saturday    Espresso        45.0 NaN
Sunday        Sunday    Espresso        45.0 NaN
Thursday    Thursday    Espresso        40.0 NaN
Wednesday  Wednesday    Espresso        35.0 NaN

In [ ]:
df.drop(columns=2,inplace=True)

In [ ]:
df.head()

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso        45.0
Saturday    Saturday    Espresso        45.0
Sunday        Sunday    Espresso        45.0
Thursday    Thursday    Espresso        40.0
Wednesday  Wednesday    Espresso        35.0